# conf_ver: 20250404
# by: hq450
# mod: black_list 优先版
# --------------------------------------------------------------------------------------------------

bind [::]:7913

# ------------ domain-set ---------------------
domain-set -name chnlist -file /tmp/chnlist.txt
domain-set -name gfwlist -file /tmp/gfwlist.txt
domain-set -name rotlist -file /koolshare/ss/rules/rotlist.txt
domain-set -name white_list -file /tmp/white_list.txt
domain-set -name black_list -file /tmp/black_list.txt
domain-set -name block_list -file /tmp/block_list.txt

# ------------ domain-rules ---------------------

# ������ black_list 优先（强制走代理）
domain-rules /domain-set:black_list/ -p #4:black_list,#6:- -c none -a #6 -n gfw -d yes

# chnlist
domain-rules /domain-set:chnlist/ -p #4:chnlist,#6:chnlist6 -c ping,tcp:80,tcp:443 -r first-ping -d yes -n chn

# white_list
domain-rules /domain-set:white_list/ -p #4:white_list,#6:white_list6 -c ping,tcp:80,tcp:443 -r first-ping -d yes -n chn

# gfwlist
domain-rules /domain-set:gfwlist/ -p #4:gfwlist,#6:- -c none -a #6 -n gfw

# rotlist
domain-rules /domain-set:rotlist/ -p #4:router,#6:- -c none -a #6 -n gfw

# block_list
domain-rules /domain-set:block_list/ -a #

# ---------------------------------------------

speed-check-mode none

cache-persist yes
cache-file /tmp/smartdns_2.cache

prefetch-domain yes

serve-expired yes
serve-expired-ttl 259200
serve-expired-reply-ttl 3

cache-checkpoint-time 86400

force-AAAA-SOA no
force-qtype-SOA 65

log-level info
log-file /tmp/smartdns_log.txt
log-size 2M
log-num 1

audit-enable yes
audit-file /tmp/smartdns_audit.txt
audit-size 2M
audit-num 1

ca-file /etc/ssl/certs/ca-certificates.crt

#--------------------------------
blacklist-ip 10.0.0.0/8
#--------------------------------

proxy-server socks5://127.0.0.1:23456 -name fancy_proxy

# chn组
server 117.50.10.10 -group chn -blacklist-ip -exclude-default-group
server 117.50.60.30 -group chn -blacklist-ip -exclude-default-group
server 223.5.5.5 -group chn -blacklist-ip -exclude-default-group
server 119.29.29.29 -group chn -blacklist-ip -exclude-default-group
server 114.114.114.114 -group chn -blacklist-ip -exclude-default-group
server 180.184.1.1 -group chn -blacklist-ip -exclude-default-group
server 1.2.4.8 -group chn -blacklist-ip -exclude-default-group
server 180.76.76.76 -group chn -blacklist-ip -exclude-default-group

# gfw组
server-tcp 8.8.8.8 -group gfw -proxy fancy_proxy
server-tcp 1.1.1.1 -group gfw -proxy fancy_proxy
# server-tls dns.google.com -group gfw -proxy fancy_proxy -host-ip 8.8.8.8
# server-tls one.one.one.one -group gfw -proxy fancy_proxy -host-ip 1.1.1.1